version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sym_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=dev

  nginx:
    image: nginx:latest
    container_name: sym_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: sym_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql

  mysql_test:
    image: mysql:8.0
    container_name: sym_mysql_test
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_test_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: sym_redis
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mysql_test_data:
  redis_data:
